Various improvements, including pagination support and additional columns for some resources
manywho/awsinventory pull request #111
Opened 2020-09-26 06:18 UTC by reedloden

* Use pagination for all API calls where supported.
* Move S3 to be a "regional" service, as while S3 bucket names are global, the actual buckets and the objects in them are stored on a per-region basis.
* Change hasRegionalServices() to use a list of globalServices (there's only one) versus a long list of regional services.
* Add ARN to all resources (which sometimes requires manually constructing it using separate calls to get the partition and account ID).
* Add missing columns and standardize existing ones for several resources.

2020-09-28 07:09 UTC, reedloden commented
I have PRs ready to post for adding Lambda, CloudFront, and DynamoDB as well, but they depend on this PR landing first to clean some stuff up. Might be worth landing this and getting the other three landed before doing a new release.

2020-10-02 19:07 UTC, reedloden commented
@itmecho Would love to get this reviewed and landed soon if you have time. :-)

2020-10-02 19:10 UTC, itmecho commented
Sorry for the delay @reedloden, if my 1 year old ever decides to sleep I'll get on this!

I hope you're registered for Hacktoberfest ;)

2020-10-02 20:04 UTC, reedloden commented
Hah, no worries.

Wasn’t aware of Hacktoberfest, so thanks for the pointer. Just registered.
:-)

On Fri, Oct 2, 2020 at 12:10 PM itmecho <notifications@github.com> wrote:

> Sorry for the delay @reedloden <https://github.com/reedloden>, if my 1
> year old ever decides to sleep I'll get on this!
>
> I hope you're registered for Hacktoberfest ;)
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/manywho/awsinventory/pull/111#issuecomment-702909825>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACV76ZGCYQXPUM4NODV2CTSIYQSXANCNFSM4R2WPGQA>
> .
>

2020-10-05 11:28 UTC, itmecho requested changes
Looks good! Could you also run `go fmt ./...` to standardize the format?

2020-10-05 11:28 UTC, itmecho commented on internal/awsdata/ebs.go
> +	out, err := ec2Svc.DescribeSecurityGroups(&ec2.DescribeSecurityGroupsInput{})
I can't see a better way of doing this at the moment but we should add `MaxResults: 5` ([5 seems to be the minimum](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#DescribeSecurityGroupsInput)) here to increase performance and reduce network load.

2020-10-05 11:28 UTC, itmecho commented on internal/awsdata/ebs.go
> +	out, err := ec2Svc.DescribeSecurityGroups(&ec2.DescribeSecurityGroupsInput{})
Actually, if it's reasonable to assume that this ID will be the same across all resources, we could use `sts.GetCallerIdentity()` to load this once at startup. What do you think?

2020-10-05 14:14 UTC, reedloden commented on internal/awsdata/ebs.go
> +	out, err := ec2Svc.DescribeSecurityGroups(&ec2.DescribeSecurityGroupsInput{})
Unfortunately, `sts.GetCallerIdentity()` doesn't work correctly for `AssumeRole`. I looked into that, as I agree that's easier. https://stackoverflow.com/questions/33791069/quick-way-to-get-aws-account-number-from-the-aws-cli-tools

2020-10-05 14:23 UTC, reedloden commented
@itmecho `go fmt` ran and `MaxResults: 5` added. :-)

2020-10-05 15:48 UTC, itmecho commented on internal/awsdata/ebs.go
> +	out, err := ec2Svc.DescribeSecurityGroups(&ec2.DescribeSecurityGroupsInput{})
Oh really? If I run the cli command with `--profile some-profile-that-assumes-a-role` I get the ID of the account associated with the role, not my user. Maybe I'm misunderstanding? I'll merge it for now anyway, we can always open another PR if it turns out to work.

2020-10-05 15:48 UTC, merged