Use the endpoints API in the SDK to load all valid regions
manywho/awsinventory pull request #95
Opened 2020-09-06 21:44 UTC by reedloden

https://aws.amazon.com/blogs/developer/using-the-aws-sdk-for-gos-regions-and-endpoints-metadata/

2020-09-09 09:10 UTC, itmecho requested changes
Great improvement! Just a little design change

2020-09-09 09:10 UTC, itmecho commented on internal/awsdata/data.go
> +	ValidRegions []string
I think this would be a good opportunity to remove these global variables (`ValidRegions` and `ValidServices`) and store the data in the `AWSData` struct instead. This change would mean that the `New` function could return an error so usages of that would need to be updated.

Also the call to `validate(Regions|Services)` further down would need to be moved to methods on the `AWSData` struct. Either that or have an extra parameter for us to pass in the valid regions to check against

2020-09-09 09:13 UTC, itmecho commented
Once this PR gets merged in, we can rebase your other PRs and update them to use the new `DefaultRegion` variable

2020-09-22 07:06 UTC, reedloden commented on internal/awsdata/data.go
> +	ValidRegions []string
@itmecho Sorry for the delay. Is the updated commit what you meant?

2020-09-23 09:42 UTC, itmecho commented on internal/awsdata/data.go
> +	ValidRegions []string
Looks good!

2020-09-23 09:43 UTC, itmecho approved these changes

2020-09-23 09:43 UTC, merged

2020-09-23 09:59 UTC, itmecho commented
@reedloden Thanks for this! If you get those other PRs rebased, I'll merge them in